LOAD TABLE USERDATA
(
	REGISTRATION_TIME,
	ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	GENDER,
	IP_ADDRESS,
	CC,
	COUNTRY,
	BIRTHDATE,
	SALARY,
	TITLE,
	COMMENTS
)
USING FILE 's3://hanacloud/userdata1.parquet', 's3://hanacloud/userdata2.parquet', 's3://hanacloud/userdata3.parquet'
FORMAT parquet
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2'
ESCAPES OFF;

SELECT * FROM USERDATA;
