LOAD TABLE WAREHOUSE
(
	W_WAREHOUSE_SK,
	W_WAREHOUSE_ID,
	W_WAREHOUSE_NAME,
	W_WAREHOUSE_SQ_FT,
	W_STREET_NUMBER,
	W_STREET_NAME,
	W_STREET_TYPE,
	W_SUITE_NUMBER,
	W_CITY,
	W_COUNTY,
	W_STATE,
	W_ZIP,
	W_COUNTRY,
	W_GMT_OFFSET
)
USING FILE 's3://hanacloud/warehouse.dat'
DELIMITED BY '|'
ROW DELIMITED BY '\x0a'
MESSAGE LOG 's3://hanacloud/warehouse.log'
ROW LOG 's3://hanacloud/warehouse.rowlog'
ONLY LOG ALL
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2'
ESCAPES OFF;

TRUNCATE TABLE WAREHOUSE;
LOAD TABLE WAREHOUSE
(
	W_WAREHOUSE_SK,
	W_WAREHOUSE_ID,
	W_WAREHOUSE_NAME,
	W_WAREHOUSE_SQ_FT,
	W_STREET_NUMBER,
	W_STREET_NAME,
	W_STREET_TYPE,
	W_SUITE_NUMBER,
	W_CITY,
	W_COUNTY,
	W_STATE,
	W_ZIP,
	W_COUNTRY,
	W_GMT_OFFSET
)
USING FILE 's3://hanacloud/warehouse.dat.gz'
DELIMITED BY '|'
ROW DELIMITED BY '\x0a'
MESSAGE LOG 's3://hanacloud/warehouse.log'
ROW LOG 's3://hanacloud/warehouse.rowlog'
ONLY LOG ALL
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2'
ESCAPES OFF;

SELECT * FROM WAREHOUSE;
