LOAD TABLE WAREHOUSE_BIN
(
	W_WAREHOUSE_SK BINARY WITH NULL BYTE,
	W_WAREHOUSE_ID BINARY WITH NULL BYTE,
	W_WAREHOUSE_NAME BINARY WITH NULL BYTE,
	W_WAREHOUSE_SQ_FT BINARY WITH NULL BYTE,
	W_STREET_NUMBER BINARY WITH NULL BYTE,
	W_STREET_NAME BINARY WITH NULL BYTE,
	W_STREET_TYPE BINARY WITH NULL BYTE,
	W_SUITE_NUMBER BINARY WITH NULL BYTE,
	W_CITY BINARY WITH NULL BYTE,
	W_COUNTY BINARY WITH NULL BYTE,
	W_STATE BINARY WITH NULL BYTE,
	W_ZIP BINARY WITH NULL BYTE,
	W_COUNTRY BINARY WITH NULL BYTE,
	W_GMT_OFFSET BINARY WITH NULL BYTE
)
USING FILE 's3://hanacloud/warehouse.unload.bin'
FORMAT BINARY
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2'
ESCAPES OFF;

SELECT * FROM WAREHOUSE_BIN;
