UNLOAD SELECT * FROM WAREHOUSE INTO FILE 's3://hanacloud/warehouse.unload'
DELIMITED BY '|'
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2';

UNLOAD SELECT * FROM WAREHOUSE INTO FILE 's3://hanacloud/warehouse.unload.bin'
FORMAT BINARY
ACCESS_KEY_ID 'AKIAIKRDGYHC2YTW64SA'
SECRET_ACCESS_KEY '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'
REGION 'us-east-2';
